# Generated by Django 5.0 on 2023-12-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=64, verbose_name="제목")),
                ("contents", models.TextField()),
                ("registered_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물",
                "db_table": "community_board",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "community_category",
                "verbose_name_plural": "categories",
                "db_table": "community_category",
            },
        ),
    ]
