# Generated by Django 5.0 on 2024-01-04 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "댓글", "verbose_name_plural": "댓글"},
        ),
    ]
