# Generated by Django 5.0 on 2023-12-24 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=64, verbose_name="제목")),
                ("contents", models.TextField()),
            ],
            options={
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물",
                "db_table": "community_board",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.board"
            ),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
