# Generated by Django 5.0 on 2023-12-26 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_board_alter_comment_post_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardFree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=64, verbose_name="제목")),
                ("contents", models.TextField()),
            ],
            options={
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물",
                "db_table": "free_board",
            },
        ),
        migrations.CreateModel(
            name="BoardQna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=64, verbose_name="제목")),
                ("contents", models.TextField()),
            ],
            options={
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물",
                "db_table": "qna_board",
            },
        ),
        migrations.RenameModel(
            old_name="Board",
            new_name="BoardAnn",
        ),
        migrations.AlterModelTable(
            name="boardann",
            table="ann_board",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.boardfree"
            ),
        ),
    ]
