# Generated by Django 5.0 on 2024-01-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_alter_comment_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="message",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="community.board",
            ),
        ),
    ]
