# Generated by Django 5.0 on 2023-12-27 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_board_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
