# Generated by Django 5.0 on 2023-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="slug",
            field=models.SlugField(max_length=64, null=True, unique=True),
        ),
    ]
