# Generated by Django 5.0 on 2024-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_rename_message_comment_content_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name=""),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
