# Generated by Django 5.0 on 2023-12-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_boardfree_boardqna_rename_board_boardann_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=64, verbose_name="제목")),
                ("contents", models.TextField()),
            ],
            options={
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물",
                "db_table": "community_board",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.DeleteModel(
            name="BoardAnn",
        ),
        migrations.DeleteModel(
            name="BoardQna",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.board"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="community.category",
            ),
        ),
        migrations.DeleteModel(
            name="BoardFree",
        ),
    ]
