# Generated by Django 5.0 on 2024-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "community",
            "0004_alter_board_registered_date_alter_comment_content_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated",
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
