# Generated by Django 5.0 on 2023-12-26 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_board_category_delete_boardann_delete_boardqna_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
