# Generated by Django 5.0 on 2023-12-27 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_board_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="slug",
        ),
    ]
