# Generated by Django 5.0 on 2023-12-26 02:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0005_remove_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 26, 2, 52, 50, 332762, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default=1, max_length=200, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="board",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="community.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[("Ann", "공지사항"), ("Free", "자유게시판"), ("Qna", "문의게시판")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
