# Generated by Django 5.0 on 2023-12-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0005_remove_board_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="writer",
            field=models.CharField(default=1, max_length=50, verbose_name="작성자"),
            preserve_default=False,
        ),
    ]
