# Generated by Django 5.0 on 2024-01-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0005_remove_comment_updated_alter_comment_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="post_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
