# Generated by Django 5.0 on 2023-12-26 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0006_board_registered_date_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 26, 4, 12, 1, 561253, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
