# Generated by Django 5.0 on 2024-01-08 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0006_board_post_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
