# Generated by Django 5.0 on 2023-12-26 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0008_alter_board_registered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 26, 7, 1, 30, 6979, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[("Ann", "공지사항"), ("Free", "자유게시판"), ("Qna", "문의게시판")],
                db_index=True,
                max_length=50,
                unique=True,
            ),
        ),
    ]
