# Generated by Django 5.0 on 2024-01-08 06:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0009_alter_board_registered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="community.category",
                verbose_name="게시판 목록",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 8, 6, 53, 37, 320547, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
