# Generated by Django 5.0 on 2023-12-26 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0010_alter_board_registered_date_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="category",
        ),
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 26, 7, 12, 8, 65592, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
