# Generated by Django 5.0 on 2024-01-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0010_alter_board_category_alter_board_registered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
