# Generated by Django 5.0 on 2023-12-26 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0014_alter_board_registered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 26, 8, 20, 15, 283807, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
