# Generated by Django 5.0 on 2023-12-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0015_alter_board_registered_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catgory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="category")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="board",
            name="registered_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
