# Generated by Django 5.0 on 2023-12-27 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0016_catgory_alter_board_registered_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catgory",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
