# Generated by Django 5.0 on 2023-12-27 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0017_alter_catgory_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catgory",
            new_name="Category",
        ),
    ]
