# Generated by Django 5.0 on 2024-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginhistory",
            name="country",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="ip",
            field=models.CharField(default="", max_length=20),
        ),
    ]
