# Generated by Django 5.0 on 2024-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_pin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin_number',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
