# Generated by Django 4.2 on 2023-12-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=90)),
                ("category", models.TextField(blank=True, null=True)),
                ("card_image", models.ImageField(upload_to="books/")),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("prologue", models.TextField(blank=True, null=True)),
                ("year_of_life", models.TextField(blank=True, null=True)),
                ("quiz", models.IntegerField(default=0)),
            ],
        ),
    ]
