# Generated by Django 5.0 on 2024-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodes",
            name="title",
        ),
        migrations.AddField(
            model_name="book",
            name="Ep_title_1",
            field=models.CharField(default=None, help_text="에피소드1", max_length=30),
        ),
        migrations.AddField(
            model_name="book",
            name="Ep_title_2",
            field=models.CharField(default=None, help_text="에피소드2", max_length=30),
        ),
        migrations.AddField(
            model_name="book",
            name="Ep_title_3",
            field=models.CharField(default=None, help_text="에피소드3", max_length=30),
        ),
    ]
