# Generated by Django 4.2 on 2023-12-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_number",
                    models.PositiveIntegerField(default=1, help_text="에피소드 번호"),
                ),
                (
                    "scene_number",
                    models.PositiveIntegerField(default=1, help_text="장면 번호"),
                ),
                (
                    "title",
                    models.CharField(default=None, help_text="에피소드 이름", max_length=30),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None, help_text="에피소드 장면 이미지", upload_to="contents/"
                    ),
                ),
                (
                    "voice",
                    models.FileField(
                        default=None, help_text="기본음성", upload_to="voices/"
                    ),
                ),
                (
                    "voice_text",
                    models.CharField(
                        default=None, help_text="음성 대사 텍스트", max_length=30
                    ),
                ),
                (
                    "quiz_text",
                    models.CharField(
                        default=None, help_text="퀴즈 문제 내용", max_length=100
                    ),
                ),
                (
                    "quiz_answer",
                    models.CharField(default=None, help_text="퀴즈 문제 정답", max_length=30),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="playground.book",
                    ),
                ),
            ],
        ),
    ]
