# Generated by Django 5.0 on 2023-12-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodes",
            name="quiz_answer",
        ),
        migrations.RemoveField(
            model_name="episodes",
            name="quiz_text",
        ),
        migrations.AlterField(
            model_name="episodes",
            name="voice_text",
            field=models.CharField(default=None, help_text="음성 대사 텍스트", max_length=100),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_index", models.IntegerField(default=None)),
                (
                    "quiz_text",
                    models.CharField(
                        default=None, help_text="퀴즈 문제 내용", max_length=1000
                    ),
                ),
                (
                    "quiz_answer",
                    models.CharField(
                        default=None, help_text="퀴즈 문제 정답", max_length=100
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="playground.book",
                    ),
                ),
            ],
        ),
    ]
