# Generated by Django 4.2 on 2024-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0002_remove_episodes_quiz_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodes",
            name="height",
            field=models.IntegerField(default=0, help_text="css height에 들어갈 높이값"),
        ),
        migrations.AddField(
            model_name="episodes",
            name="image_segment",
            field=models.ImageField(
                default=None, help_text="인물 테두리 이미지", upload_to="contents/"
            ),
        ),
        migrations.AddField(
            model_name="episodes",
            name="width",
            field=models.IntegerField(default=0, help_text="css width에 들어갈 넓이값"),
        ),
        migrations.AddField(
            model_name="episodes",
            name="x_index",
            field=models.IntegerField(default=0, help_text="css right 에 들어갈 x 값"),
        ),
        migrations.AddField(
            model_name="episodes",
            name="y_index",
            field=models.IntegerField(default=0, help_text="css top 에 들어갈 y 값"),
        ),
    ]
