# Generated by Django 5.0 on 2023-12-29 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0002_episode"),
        ("playground", "0002_episodes"),
    ]

    operations = []
